### ISSUE TITLE
Error when building collection locally

### ISSUE THREAD

**Issue by etanus11** [CollectionBuilder/collectionbuilder-sa#4]
HI, I created a collection from the collectionbuiler-sa. When building the site I get the following error message:
jekyll b --incremental
Configuration file: /var/www/html/namib_desert/_config.yml
            Source: /var/www/html/namib_desert
       Destination: /var/www/html/namib_desert/_site
 Incremental build: enabled
      Generating... 
jekyll 3.1.6 | Error:  no implicit conversion of String into Integer
---- ~/www/namib_desert$ rake deploy --trace
** Invoke deploy (first_time)
** Execute deploy
jekyll build
Configuration file: /var/www/html/namib_desert/_config.yml
            Source: /var/www/html/namib_desert
       Destination: /var/www/html/namib_desert/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
jekyll 3.1.6 | Error:  no implicit conversion of String into Integer
rake aborted!
Command failed with status (1): [jekyll build...]
/usr/lib/ruby/vendor_ruby/rake/file_utils.rb:67:in `block in create_shell_runner'
/usr/lib/ruby/vendor_ruby/rake/file_utils.rb:57:in `sh'
/var/www/html/namib_desert/Rakefile:10:in `block in <top (required)>'
/usr/lib/ruby/vendor_ruby/rake/task.rb:271:in `block in execute'
/usr/lib/ruby/vendor_ruby/rake/task.rb:271:in `each'
/usr/lib/ruby/vendor_ruby/rake/task.rb:271:in `execute'
/usr/lib/ruby/vendor_ruby/rake/task.rb:213:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/usr/lib/ruby/vendor_ruby/rake/task.rb:193:in `invoke_with_call_chain'
/usr/lib/ruby/vendor_ruby/rake/task.rb:182:in `invoke'
/usr/lib/ruby/vendor_ruby/rake/application.rb:160:in `invoke_task'
/usr/lib/ruby/vendor_ruby/rake/application.rb:116:in `block (2 levels) in top_level'
/usr/lib/ruby/vendor_ruby/rake/application.rb:116:in `each'
/usr/lib/ruby/vendor_ruby/rake/application.rb:116:in `block in top_level'
/usr/lib/ruby/vendor_ruby/rake/application.rb:125:in `run_with_threads'
/usr/lib/ruby/vendor_ruby/rake/application.rb:110:in `top_level'
/usr/lib/ruby/vendor_ruby/rake/application.rb:83:in `block in run'
/usr/lib/ruby/vendor_ruby/rake/application.rb:186:in `standard_exception_handling'
/usr/lib/ruby/vendor_ruby/rake/application.rb:80:in `run'
/usr/bin/rake:27:in `<main>'
Tasks: TOP => deploy
Please help.
Renate

**Comment by dcnb** [comment]
Hi Renate,

your _config.yml file uses an extension on the 'metadata' variable.

right now you have -->  sperrgebiet_new.csv

That should be --> sperrgebiet_new

**Comment by evanwill** [comment]
@etanus11 one more tweak-- @dcnb mentioned not using an extension when naming the metadata file in "_config.yml", but that name is used twice in collectionbuilder-sa (only once in -gh), so make sure to NOT use an extension on both:
1st for `metadata: sperrgebiet_new`
2nd in `page_gen` settings, `- data: 'sperrgebiet_new'`

So the updated "Collection Settings" section of your "_config.yml" will look like:

```
# choose metadata: this is the name of the csv file in your _data directory that describes the objects in your collection
metadata: sperrgebiet_new
# page generation settings 
# "data" value must be the name of the metadata file (other values should be not be changed)
page_gen:
  - data: 'sperrgebiet_new'
    template: 'items'
    name: 'objectid'
    dir: 'items'
    extension: 'html' 
    filter: 'objectid'  
```
